[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1


[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
let g:neosnippet#snippets_directory='~/.cache/neosnippet-snippets/neosnippets'
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']


[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let g:NERDTreeShowBookmarks=1
  let g:NERDTreeShowHidden = 1
'''


[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
depends = ['nerdtree']
hook_add = '''
let g:nerdtree_tabs_open_on_console_startup=1
map <C-n> : NERDTreeTabsToggle<CR>
'''


[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['nerdtree']


# [[plugins]]
# repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
# depends = ['nerdtree']


[[plugins]]
repo = 'Shougo/unite.vim'


[[plugins]]
repo = 'Shougo/neomru.vim'


[[plugins]]
repo = 'zchee/deoplete-jedi'
hook_add = '''
  autocmd FileType python setlocal completeopt-=preview 
'''
depends = ['deoplete.nvim']
on_ft = ['python']


[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = ''' 
let g:quickrun_config = get(g:, 'quickrun_config', {})
let g:quickrun_config._ = {
      \ 'runner'    : 'vimproc',
      \ 'runner/vimproc/updatetime' : 60,
      \ 'outputter' : 'error',
      \ 'outputter/error/success' : 'buffer',
      \ 'outputter/error/error'   : 'quickfix',
      \ 'outputter/buffer/split'  : ':rightbelow 8sp',
      \ 'outputter/buffer/close_on_empty' : 1,
      \ }
au FileType qf nnoremap <silent><buffer>q :quit<CR>
let g:quickrun_no_default_key_mappings = 1
nnoremap <Leader>r :cclose<CR>:write<CR>:QuickRun -mode n<CR>
xnoremap <Leader>r :<C-U>cclose<CR>:write<CR>gv:QuickRun -mode v<CR>
nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"
'''
