[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'freeo/vim-kalisi'

[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo= 'airblade/vim-gitgutter'

[[plugins]]
repo = 'vim-airline/vim-airline'
